[build]
  command = "npm install --force && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.20.5"  # Specify exact version instead of '18.x'