[build]
  command = "npm install --force && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.20.5"
  NPM_VERSION = "10.8.2"
  NEXT_TELEMETRY_DISABLED = "1"

[functions]
  node_bundler = "esbuild"